### ISSUE TITLE
Shivering sound effect loops indefinitely

### ISSUE THREAD

**Issue by BruceJohnJennerLawso** [angrmgmt/skyui-vr#2]
Having difficulty pinning this bug down perfectly, but basically every now and then when doing something frosty, then recovering in front of a heat source my character will get locked to maximum exposure and will never recover. Checking the MCM for frostfall, my stats will be at +20 exposure, 0 wetness, and the damn shivering/freezing/stuttered breathing sound effect will start looping constantly.

Its very odd because it happens even when I specifically deactivate sound effects in the Frostfall MCM, and it seems to like to occur when hitting "full warmth" after being cold, ie when standing right in front of a fire.

Not sure if a bug with the VR patch, or just with Frostfall in general, but its driving me crazy

**Comment by angrmgmt** [comment]
That is wild... and I'm gonna level with you:  I have no idea why that would happen.  Basically, all I did was add the Campfire/Frostfall UI elements back in, since the new SkyUI-VR has a slightly different layout and the button names and whatnot can change depending on the HMD and/or controller used.  Everything except the meters, that is; those widgets aren't implemented yet so I couldn't add them, and instead relied on the text messages in the top left to do that work.  I didn't change how assets are loaded, especially not audio assets.  You might have a conflict elsewhere.

Best advice I can give is to check that nothing is overwriting any of the UI files (the .swf files), which were what I modified, though I'm not sure that will help.  Maybe check the SKSE logs for anything that seems amiss.  I no longer have the toolchain to make changes to this and have handed it off to @Odie, who I think has been satisfied with the current state since then...

Sorry you're having trouble with it, though.  That sounds like a real headache!

**Comment by BruceJohnJennerLawso** [comment]
> That is wild... and I'm gonna level with you: I have no idea why that would happen. Basically, all I did was add the Campfire/Frostfall UI elements back in, since the new SkyUI-VR has a slightly different layout and the button names and whatnot can change depending on the HMD and/or controller used. Everything except the meters, that is; those widgets aren't implemented yet so I couldn't add them, and instead relied on the text messages in the top left to do that work. I didn't change how assets are loaded, especially not audio assets. You might have a conflict elsewhere.
> 
> Best advice I can give is to check that nothing is overwriting any of the UI files (the .swf files), which were what I modified, though I'm not sure that will help. Maybe check the SKSE logs for anything that seems amiss. I no longer have the toolchain to make changes to this and have handed it off to @Odie, who I think has been satisfied with the current state since then...
> 
> Sorry you're having trouble with it, though. That sounds like a real headache!

Sorry about the somewhat vague bug report, I was still trying to pin it down as I was submitting. VR is not the fastest environment for testing

I suspect its a bug with Frostfall/Skyrim itself, as I read many old threads with people complaining of never ending sound loops stuck on in vanilla skyrim. Many also claim its fixable by running 'sexchange' twice in the console.

Im ok for now, the sound started up briefly but then stopped again, so idk.

Its just peculiar, because it happens even after Ive explicitly disabled sound effects in the Frostfall MCM, and everything else seems to run just fine. I can jump into a lake, get out start a fire, dry out, then jump in the lake again and freeze to death, and everything works the way its supposed to except for the looping shivering sound

Thanks for your time

**Comment by BruceJohnJennerLawso** [comment]
Can confirm the sexchange command workaround is effective, probably resets all sounds in the game while switching between male/female sound effect sets.
